#!/bin/sh
#
# requires Hammerspoon < https://www.hammerspoon.org/ >
# and the PhotosServer spoon < https://github.com/heckman/PhotosServer.spoon >
hs -q -c "
hs.json.encode(
	hs.loadSpoon'PhotosServer'.getSelection(
		$(test $# -ne 0 && printf "'%s'," "$@" | sed 's/,$//')
	),
	true
)
"
